services:
  desktop:
    container_name: desktop
    image: ghcr.io/amitie10g/kali-rolling:latest
    restart: always
    ports:
      - 3389:3389
    volumes:
      - ./kali/kali:/home/kali
      - ./kali/root:/root

  vulnerable-webapps:
    container_name: vulnerable
    image: ghcr.io/amitie10g/kali-rolling:labs
    restart: always
