name: Cleanup Docker repositories
on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Drop untagged packages
      uses: actions/delete-package-versions@v5
      with: 
        package-name: 'kali'
        package-type: 'container'
        delete-only-untagged-versions: 'true'
    - name: Drop untagged packages
      uses: actions/delete-package-versions@v5
      with: 
        package-name: 'kali-rolling'
        package-type: 'container'
        delete-only-untagged-versions: 'true'
    - name: Drop untagged packages
      uses: actions/delete-package-versions@v5
      with: 
        package-name: 'kali-bleeding-edge'
        package-type: 'container'
        delete-only-untagged-versions: 'true'
    - name: Cleanup Docker cache image
      run: |
        curl -X DELETE -H "Authorization: token ${{ secrets.PACKAGE_DELETE_TOKEN }}" \
          https://api.github.com/user/packages/container/kali-cache
